min_freq: 2
tokenizer: sentencepiece
tokenizer_model_type: bpe
tokenizer_vocab_size: 32000
src_tokenizer_prefix: tokenizers/src
tgt_tokenizer_prefix: tokenizers/tgt

special_tokens:
  pad: "<PAD>"
  sos: "<SOS>"
  eos: "<EOS>"
  unk: "<UNK>"
