batch_size: 32
epochs: 50
learning_rate: 0.0001
use_transformer_lr_scheduler: true
warmup_steps: 4000
scheduler_factor: 1.0

pad_idx: 0

weight_decay: 0.0
gradient_clip: 1.0

save_every: 5
device: cuda
